#!/bin/sh
#
# Copyright © 2015-2024 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running on Alpine/Linux (iSH):
#   We add the line "export GRADLE_OPTS='-Xmx64m -Xms64m'" to limit memory.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
APP_PATH="${0##*/}"
APP_HOME="${0%/*}"
if [ "$APP_HOME" = "$APP_PATH" ] || [ ! -d "$APP_HOME" ]; then
    APP_HOME=$(cd "${APP_HOME:-.}" && pwd)
fi

# Use Java from the PATH, or fallback
if ! command -v java >/dev/null 2>&1; then
    echo "Java not found. Please install JDK (apk add openjdk11) if you run this locally."
    echo "GitHub Actions will provide its own Java."
    exit 1
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the Java executable
JAVA_CMD="java"

# Use the Gradle wrapper jar
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptor limit if possible.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" = "unlimited" -o "$MAX_FD_LIMIT" = "4096" ] ; then
            ulimit -n 4096
        else
            ulimit -n "$MAX_FD_LIMIT"
        fi
    fi
fi

# For Alpine/iSH, we override memory options to prevent fatal crashes
export GRADLE_OPTS='-Xmx64m -Xms64m'

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
